@endpont = http://127.0.0.1:5001/fastify-todo-list-1707f/us-central1/todoList
@todoListId = fp79bnlqc90p

##
GET  {{endpont}}/todo
Content-Type: application/json

###

##
POST {{endpont}}/todo
Content-Type: application/json

{
  "todoListId": "{{todoListId}}",
  "title": "test-todo",
  "detail": "test-detail",
  "status": "UPCOMING",
  "createdBy": "Richie"
}

###